import type { Metadata } from "next";
import { Rubik_Glitch } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const rubikGlitch = Rubik_Glitch({
  variable: "--font-rubik-glitch",
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  // style: ["normal],
  preload: true,
});

const agrandirRegular = localFont({
  src: "../public/fonts/Agrandir-Regular.otf",
  variable: "--font-agrandir-regular",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${rubikGlitch.variable} ${agrandirRegular.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
